<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Nombre: Hiba Samraoui Samraoui
Curso: DAM1
Fecha: 03/04/2025
Ejercicio: Ejercicios 1-9
-->
<!DOCTYPE sistemaSolar [
    <!ELEMENT sistemaSolar (cuerpo+)>
    <!ELEMENT cuerpo (planeta | satelite | asteroide)>
    <!ELEMENT planeta (#PCDATA)>
    <!ELEMENT satelite (#PCDATA)>
    <!ELEMENT asteroide (#PCDATA)>
]>
<sistemaSolar>
    <cuerpo>
        <planeta>Tierra</planeta>
    </cuerpo>
    <cuerpo>
        <satelite>Luna</satelite>
    </cuerpo>
    <cuerpo>
        <asteroide>Ceres</asteroide>
    </cuerpo>
</sistemaSolar>