<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Nombre: Hiba Samraoui Samraoui
Curso: DAM1
Fecha: 28/03/2025 
Ejercicio: Ejercicio 2 
-->
<!DOCTYPE EquiposNBA [
    <!ELEMENT EquiposNBA (equipo+)>
    <!ELEMENT equipo (nombre, titulos, posicion, quinteto)>
    <!ATTLIST equipo conferencia CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT titulos (#PCDATA)>
    <!ELEMENT posicion (#PCDATA)>
    <!ELEMENT quinteto (#PCDATA)>
]>

<EquiposNBA>
    <equipo conferencia="Este">
        <nombre>Boston Celtics</nombre>
        <titulos>17</titulos>
        <posicion>1</posicion>
        <quinteto>Jayson Tatum, Jaylen Brown, Jrue Holiday, Kristaps Porzingis, Al Horford</quinteto>
    </equipo>
    
    <equipo conferencia="Oeste">
        <nombre>Los Angeles Lakers</nombre>
        <titulos>17</titulos>
        <posicion>5</posicion>
        <quinteto>LeBron James, Anthony Davis, D'Angelo Russell, Austin Reaves, Rui Hachimura</quinteto>
    </equipo>
    
    <equipo conferencia="Oeste">
        <nombre>Golden State Warriors</nombre>
        <titulos>6</titulos>
        <posicion>3</posicion>
        <quinteto>Stephen Curry, Klay Thompson, Andrew Wiggins, Draymond Green, Kevon Looney</quinteto>
    </equipo>
</EquiposNBA>
