<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Nombre: Hiba Samraoui Samraoui
Curso: DAM1
Fecha: 03/04/2025
Ejercicio: Ejercicios 1-8
-->
<!DOCTYPE agenda [
    <!ELEMENT agenda (contacto+)>
    <!ELEMENT contacto (nombre, telefonoFijo, telefonoMovil?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT telefonoFijo (#PCDATA)>
    <!ELEMENT telefonoMovil (#PCDATA)>
]>
<agenda>
    <contacto>
        <nombre>Ayuntamiento</nombre>
        <telefonoFijo>010</telefonoFijo>
    </contacto>
    <contacto>
        <nombre>Emergencias</nombre>
        <telefonoFijo>112</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil>
    </contacto>
    <contacto>
        <telefonoFijo>911</telefonoFijo>
    </contacto>
</agenda>