=== HibaSam611/DTD/Validación XML - DTD III/cuento.dtd
<!-- Nombre: Hiba Samraoui Samraoui 
Curso: DAM1 Fecha: 28/03/2025 
Ejercicio: Ejercicio 1 --> 
<!ELEMENT cuento (personajes, trama, etiqueta*, precio?)>
<!ATTLIST cuento
    cod CDATA #REQUIRED
    titulo CDATA #REQUIRED
    genero (infantil | fantasia | terror) #IMPLIED>

<!ELEMENT personajes (personaje+)>
<!ELEMENT personaje (nombre, genero, descripcion_fisica?, imagen?, url?)>
<!ATTLIST personaje
    id ID #REQUIRED
    tipo (principal | secundario | antagonista) "principal">

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT descripcion_fisica (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT trama (#PCDATA)>
<!ELEMENT etiqueta EMPTY>
<!ATTLIST etiqueta nombre CDATA #REQUIRED>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA "eur">

=== HibaSam611/DTD/Validación XML - DTD III/GatoConBotas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Nombre: Hiba Samraoui Samraoui 
Curso: DAM1 Fecha: 28/03/2025 
Ejercicio: Ejercicio 1 --> 
<!DOCTYPE cuento SYSTEM "cuento.dtd">
<cuento cod="A01" titulo="El Gato con Botas" genero="fantasía">
    <personajes>
        <personaje id="p1" tipo="principal">
            <nombre>Gato con Botas</nombre>
            <genero>M</genero>
            <descripcion_fisica>Un gato astuto y elegante que lleva botas y un sombrero.</descripcion_fisica>
        </personaje>
        <personaje id="p2" tipo="secundario">
            <nombre>El Molinero</nombre>
            <genero>M</genero>
        </personaje>
        <personaje id="p3" tipo="antagonista">
            <nombre>El Ogro</nombre>
            <genero>M</genero>
            <descripcion_fisica>Un ogro grande y feroz que vive en un castillo.</descripcion_fisica>
        </personaje>
    </personajes>
    <trama>Un gato astuto ayuda a su dueño a convertirse en un noble.</trama>
    <etiqueta nombre="clásico"/>
    <etiqueta nombre="animales"/>
    <precio moneda="eur">12.99</precio>
</cuento>

=== HibaSam611/DTD/Validación XML - DTD III/CasaEspiritus.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Nombre: Hiba Samraoui Samraoui 
Curso: DAM1 Fecha: 28/03/2025 
Ejercicio: Ejercicio 1 --> 
<!DOCTYPE cuento SYSTEM "cuento.dtd">
<cuento cod="B02" titulo="La Casa de los Espíritus" genero="terror">
    <personajes>
        <personaje id="p1" tipo="principal">
            <nombre>Clara</nombre>
            <genero>F</genero>
            <descripcion_fisica>Una mujer con habilidades psíquicas.</descripcion_fisica>
        </personaje>
        <personaje id="p2" tipo="secundario">
            <nombre>Esteban Trueba</nombre>
            <genero>M</genero>
        </personaje>
    </personajes>
    <trama>La historia de una familia a lo largo de varias generaciones, marcada por el amor y la tragedia.</trama>
    <etiqueta nombre="realismo mágico"/>
    <precio>15.50</precio>
</cuento>
