<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Nombre: Hiba Samraoui Samraoui
Curso: 1ºDAM
Fecha: 06/04/2025 
Ejercicio: Ejercicio 8
-->

<!DOCTYPE contabilidad [ 
    <!ELEMENT contabilidad (apunte*)> <!-- El elemento contabilidad debe contener 0 o más apuntes -->
    <!ELEMENT apunte (ingreso | gasto)> 
    <!ELEMENT ingreso (fecha, cantidad, concepto)> <!-- El elemento ingreso debe contener fecha, cantidad y concepto -->
    <!ELEMENT gasto (fecha, cantidad, concepto)> <!-- El elemento gasto debe contener fecha, cantidad y concepto -->
    <!ELEMENT fecha (#PCDATA)> <!-- El elemento fecha debe contener texto -->
    <!ELEMENT cantidad (#PCDATA)> 
    <!ELEMENT concepto (#PCDATA)> 
]>

<contabilidad>
    <apunte>
        <ingreso>
            <fecha>24 de febrero de 2011</fecha>
            <cantidad>1800,00 €</cantidad>
            <concepto>Salario</concepto>
        </ingreso>
    </apunte>
    <apunte>
        <gasto>
            <fecha>28 de febrero de 2011</fecha>
            <cantidad>74,25 €</cantidad>
            <concepto>Recibo luz</concepto>
        </gasto>
    </apunte>
</contabilidad>